// apps/web-angular/src/app/pages/home.page.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import type { AnizoneSearchItem, ContinueWatchingItem, FavoriteEntry, Movie, Series } from '@streaming/types';
import type { AnizoneSearchResult } from '@streaming/types';
import { ApiService } from '../core/api.service';
import { ProfileService } from '../core/profile.service';
import { FocusableDirective } from '../tv/focusable.directive';
import { DefaultFocusDirective } from '../tv/default-focus.directive';
import { RowComponent } from '../components/row.component';
import { ContentCardComponent } from '../components/content-card.component';
import { AnizoneResultCardComponent } from '../components/anizone-result-card.component';
import { AnizonePreviewModalComponent } from '../components/anizone-preview-modal.component';
import { SkeletonRowComponent } from '../components/skeleton-row.component';
import { IconComponent } from '../components/icon.component';

type HeroItem = {
  title: string;
  meta: string;
  description?: string | null;
  backdropUrl?: string | null;
  primaryLabel: string;
  primaryUrl?: string;
  previewSeries?: Series;
};

type PreviewState = { series?: Series; searchItem?: AnizoneSearchItem };

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [
    FormsModule,
    FocusableDirective,
    DefaultFocusDirective,
    RowComponent,
    ContentCardComponent,
    AnizoneResultCardComponent,
    AnizonePreviewModalComponent,
    SkeletonRowComponent,
    IconComponent,
  ],
  templateUrl: './home.page.html',
  styleUrl: './home.page.scss',
})
export class HomePageComponent {
  private api = inject(ApiService);
  private profileService = inject(ProfileService);
  private router = inject(Router);

  protected Math = Math;
  activeProfile = this.profileService.activeProfile;

  searchInput = '';
  submittedQuery = signal('');
  importingSlug = signal<string | null>(null);
  preview = signal<PreviewState | null>(null);

  continueWatching = signal<ContinueWatchingItem[]>([]);
  series = signal<Series[]>([]);
  movies = signal<Movie[]>([]);
  favorites = signal<FavoriteEntry[]>([]);
  searchResults = signal<AnizoneSearchResult | undefined>(undefined);
  searching = signal(false);
  searchError = signal(false);
  initialLoading = signal(true);

  constructor() {
    const profileId = this.activeProfile()!.id;
    Promise.all([
      this.api.getContinueWatching(profileId).then((v) => this.continueWatching.set(v)),
      this.api.getSeriesList().then((v) => this.series.set(v)),
      this.api.getMovies().then((v) => this.movies.set(v)),
      this.api.getFavorites(profileId).then((v) => this.favorites.set(v)),
    ]).finally(() => this.initialLoading.set(false));
  }

  heroItem(): HeroItem | null {
    const cw = this.continueWatching()[0];
    if (cw) {
      return {
        title: cw.kind === 'episode' ? cw.seriesTitle ?? cw.title : cw.title,
        meta:
          cw.kind === 'episode' && cw.seasonNumber != null
            ? `Continue Watching · S${cw.seasonNumber} E${cw.episodeNumber}`
            : 'Continue Watching',
        backdropUrl: cw.backdropUrl ?? cw.posterUrl,
        primaryLabel: 'Resume',
        primaryUrl: `/watch/${cw.kind}/${cw.episodeId ?? cw.movieId}`,
      };
    }
    const s = this.series()[0];
    if (s) {
      return {
        title: s.title,
        meta: 'Series' + (s.releaseYear ? ` · ${s.releaseYear}` : ''),
        description: s.description,
        backdropUrl: s.backdropUrl ?? s.posterUrl,
        primaryLabel: 'View',
        previewSeries: s,
      };
    }
    const m = this.movies()[0];
    if (m) {
      return {
        title: m.title,
        meta: 'Movie' + (m.releaseYear ? ` · ${m.releaseYear}` : ''),
        description: m.description,
        backdropUrl: m.backdropUrl ?? m.posterUrl,
        primaryLabel: 'Play',
        primaryUrl: `/watch/movie/${m.id}`,
      };
    }
    return null;
  }

  activateHero(hero: HeroItem): void {
    if (hero.previewSeries) {
      this.openSeriesPreview(hero.previewSeries);
    } else if (hero.primaryUrl) {
      this.navigate(hero.primaryUrl);
    }
  }

  navigate(url: string): void {
    this.router.navigateByUrl(url);
  }

  switchProfile(): void {
    this.profileService.clearActiveProfile();
    this.router.navigateByUrl('/profiles');
  }

  isInLibrary(item: AnizoneSearchItem): boolean {
    return this.series().some((s) => s.sourceSlug === item.slug);
  }

  matchedSeriesFor(item: AnizoneSearchItem): Series | undefined {
    return this.series().find((s) => s.sourceSlug === item.slug);
  }

  favoriteEntryFor(series: Series): FavoriteEntry | undefined {
    return this.favorites().find((f) => f.seriesId === series.id);
  }

  openSeriesPreview(series: Series): void {
    this.preview.set({ series });
  }

  openSearchPreview(item: AnizoneSearchItem): void {
    this.preview.set({ searchItem: item, series: this.matchedSeriesFor(item) });
  }

  trackCw(item: ContinueWatchingItem): string {
    return item.episodeId ?? item.movieId ?? item.title;
  }

  async handleSearchSubmit(e: Event): Promise<void> {
    e.preventDefault();
    const query = this.searchInput.trim();
    this.submittedQuery.set(query);
    if (!query) return;
    this.searching.set(true);
    this.searchError.set(false);
    try {
      const results = await this.api.searchAnizone(query);
      this.searchResults.set(results);
    } catch {
      this.searchError.set(true);
      this.searchResults.set(undefined);
    } finally {
      this.searching.set(false);
    }
  }

  async handleImport(item: AnizoneSearchItem): Promise<void> {
    this.importingSlug.set(item.slug);
    try {
      const imported = await this.api.importAnizoneSeries({
        slug: item.slug,
        title: item.title,
        sourceUrl: item.sourceUrl,
        coverUrl: item.coverUrl ?? undefined,
        startYear: item.startYear ?? undefined,
      });
      const refreshed = await this.api.getSeriesList();
      this.series.set(refreshed);
      // Flip the still-open modal straight into its "in library" state
      // (full episode list, Play/Favorite) instead of requiring a re-open.
      this.preview.set({ searchItem: item, series: refreshed.find((s) => s.id === imported.id) ?? imported });
    } catch {
      // best-effort — the modal just stays on "+ Add to Library" so the user can retry
    } finally {
      this.importingSlug.set(null);
    }
  }

  async toggleFavorite(series: Series): Promise<void> {
    const profileId = this.activeProfile()!.id;
    const entry = this.favoriteEntryFor(series);
    if (entry) {
      await this.api.removeFavorite(profileId, entry.id);
    } else {
      await this.api.addFavorite(profileId, { seriesId: series.id });
    }
    const refreshed = await this.api.getFavorites(profileId);
    this.favorites.set(refreshed);
  }
}

// apps/web/src/pages/HomePage.tsx
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import type { AnizoneSearchItem } from "@streaming/types";
import { apiClient } from "../lib/apiClient";
import { useProfileStore } from "../store/useProfileStore";
import { Row } from "../components/Row";
import { ContentCard } from "../components/ContentCard";
import { AnizoneResultCard } from "../components/AnizoneResultCard";
import { AnizonePreviewModal } from "../components/AnizonePreviewModal";
import { Focusable } from "../tv-navigation/Focusable";

export function HomePage() {
  const navigate = useNavigate();
  const activeProfile = useProfileStore((s) => s.activeProfile)!;
  const clearActiveProfile = useProfileStore((s) => s.clearActiveProfile);
  const queryClient = useQueryClient();

  const [searchInput, setSearchInput] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const [importingSlug, setImportingSlug] = useState<string | null>(null);
  const [previewItem, setPreviewItem] = useState<AnizoneSearchItem | null>(null);

  const continueWatching = useQuery({
    queryKey: ["continue-watching", activeProfile.id],
    queryFn: () => apiClient.getContinueWatching(activeProfile.id),
  });
  const series = useQuery({ queryKey: ["series"], queryFn: () => apiClient.getSeriesList() });
  const movies = useQuery({ queryKey: ["movies"], queryFn: () => apiClient.getMovies() });
  const favorites = useQuery({
    queryKey: ["favorites", activeProfile.id],
    queryFn: () => apiClient.getFavorites(activeProfile.id),
  });

  // Scraped from AniZone on demand — not something to pre-fetch, each search
  // drives a real headless browser on the API side (~a few seconds).
  const searchResults = useQuery({
    queryKey: ["anizone-search", submittedQuery],
    queryFn: () => apiClient.searchAnizone(submittedQuery),
    enabled: !!submittedQuery,
    retry: 0,
  });

  function handleSearchSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmittedQuery(searchInput.trim());
  }

  async function handleImport(item: AnizoneSearchItem) {
    setImportingSlug(item.slug);
    try {
      await apiClient.importAnizoneSeries({
        slug: item.slug,
        title: item.title,
        sourceUrl: item.sourceUrl,
        coverUrl: item.coverUrl ?? undefined,
        startYear: item.startYear ?? undefined,
      });
      // matchedSeries below is derived straight from this query, so once it
      // refetches the (now open) preview modal flips to its "in library" state.
      queryClient.invalidateQueries({ queryKey: ["series"] });
    } catch {
      // best-effort — the modal just stays on "+ Add to Library" so the user can retry
    } finally {
      setImportingSlug(null);
    }
  }

  const previewMatchedSeries = previewItem
    ? series.data?.find((s) => s.sourceSlug === previewItem.slug)
    : undefined;

  return (
    <div className="screen">
      <div className="app-header">
        <span className="brand">PrivateFlix</span>
        <Focusable
          onClick={() => {
            clearActiveProfile();
            navigate("/profiles");
          }}
        >
          {activeProfile.name} · Switch profile
        </Focusable>
      </div>

      <form className="search-bar" onSubmit={handleSearchSubmit}>
        <input
          type="search"
          placeholder="Search AniZone for anime to add…"
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
          autoFocus
        />
        <Focusable type="submit" disabled={!searchInput.trim() || searchResults.isFetching}>
          {searchResults.isFetching ? "Searching…" : "Search"}
        </Focusable>
      </form>

      {searchResults.isError && (
        <p className="error-text">Couldn't reach AniZone — try again in a moment.</p>
      )}
      {submittedQuery && !searchResults.isFetching && searchResults.data?.items.length === 0 && (
        <p>No results for "{submittedQuery}".</p>
      )}

      {!!searchResults.data?.items.length && (
        <Row title={`Results for "${submittedQuery}"`}>
          {searchResults.data.items.map((item) => (
            <AnizoneResultCard
              key={item.slug}
              item={item}
              isInLibrary={!!series.data?.some((s) => s.sourceSlug === item.slug)}
              onClick={() => setPreviewItem(item)}
            />
          ))}
        </Row>
      )}

      {!!continueWatching.data?.length && (
        <Row title="Continue Watching">
          {continueWatching.data.map((item) => (
            <ContentCard
              key={`${item.kind}-${item.episodeId ?? item.movieId}`}
              title={item.kind === "episode" ? `${item.seriesTitle} — ${item.title}` : item.title}
              imageUrl={item.posterUrl}
              progressRatio={item.positionSeconds / Math.max(item.durationSeconds, 1)}
              onClick={() =>
                navigate(`/watch/${item.kind}/${item.episodeId ?? item.movieId}`)
              }
            />
          ))}
        </Row>
      )}

      {!!favorites.data?.length && (
        <Row title="Favorites">
          {favorites.data.map((entry) => {
            const content = entry.series ?? entry.movie;
            if (!content) return null;
            return (
              <ContentCard
                key={entry.id}
                title={content.title}
                imageUrl={content.posterUrl}
                onClick={() =>
                  navigate(entry.series ? `/series/${entry.series.id}` : `/watch/movie/${entry.movie!.id}`)
                }
              />
            );
          })}
        </Row>
      )}

      {!!series.data?.length && (
        <Row title="Series">
          {series.data.map((s) => (
            <ContentCard
              key={s.id}
              title={s.title}
              imageUrl={s.posterUrl}
              onClick={() => navigate(`/series/${s.id}`)}
            />
          ))}
        </Row>
      )}

      {!!movies.data?.length && (
        <Row title="Movies">
          {movies.data.map((m) => (
            <ContentCard
              key={m.id}
              title={m.title}
              imageUrl={m.posterUrl}
              onClick={() => navigate(`/watch/movie/${m.id}`)}
            />
          ))}
        </Row>
      )}

      {previewItem && (
        <AnizonePreviewModal
          item={previewItem}
          matchedSeries={previewMatchedSeries}
          continueWatching={continueWatching.data}
          isImporting={importingSlug === previewItem.slug}
          onImport={() => handleImport(previewItem)}
          onClose={() => setPreviewItem(null)}
        />
      )}
    </div>
  );
}
