// apps/web-angular/src/app/pages/login.page.ts
import { Component, inject, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { FocusableDirective } from '../tv/focusable.directive';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [FormsModule, FocusableDirective],
  templateUrl: './login.page.html',
  styleUrl: './login.page.scss',
})
export class LoginPageComponent {
  private auth = inject(AuthService);
  private router = inject(Router);

  username = '';
  password = '';
  error = signal<string | null>(null);
  loading = signal(false);

  async handleSubmit(e: Event): Promise<void> {
    e.preventDefault();
    this.error.set(null);
    this.loading.set(true);
    try {
      await this.auth.login(this.username, this.password);
      this.router.navigateByUrl('/profiles', { replaceUrl: true });
    } catch (err) {
      this.error.set(
        err instanceof HttpErrorResponse
          ? (err.error?.message ?? err.message)
          : 'Could not log in. Check the API is running.'
      );
    } finally {
      this.loading.set(false);
    }
  }
}

// apps/web/src/pages/LoginPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ApiError } from "@streaming/api-client";
import { useAuthStore } from "../store/useAuthStore";
import { Focusable } from "../tv-navigation/Focusable";

export function LoginPage() {
  const login = useAuthStore((s) => s.login);
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      await login(email, password);
      navigate("/profiles", { replace: true });
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not log in. Check the API is running.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="screen">
      <form className="login-form" onSubmit={handleSubmit}>
        <h1>PrivateFlix</h1>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoFocus
          required
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        {error && <p className="error-text">{error}</p>}
        <Focusable type="submit" disabled={loading}>
          {loading ? "Signing in…" : "Sign in"}
        </Focusable>
      </form>
    </div>
  );
}
